repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v4.3.7
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/thoughtworks/talisman # detect and prevent secrets from getting checked in
    rev: v1.11.0
    hooks:
      - id: talisman-commit
