---
roles:
  - name: gantsign.oh-my-zsh
  - name: geerlingguy.docker
  - name: geerlingguy.firewall
  - name: geerlingguy.git
  - name: geerlingguy.pip
  - name: geerlingguy.swap
  - name: geerlingguy.nginx
  - name: geerlingguy.repo-epel
  - name: geerlingguy.certbot

collections:
  - name: community.general
  - name: ansible.posix
