---
- name: Install system wide dependencies
  hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install EPEL repo
      yum:
        name: epel-release
        state: present

    - name: Make sure we have 'wheel, admin' groups
      with_items:
        - wheel
        - admin
      group:
        name: "{{ item }}"
        state: present

    - name: Allow 'wheel, admin' groups to have passwordless sudo
      with_items:
        - wheel
        - admin
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%{{ item }}"
        line: "%{{ item }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    # User + Key Setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        state: present
        groups:
          - wheel
          - admin
        append: true
        create_home: true
        shell: /bin/bash

    # - name: Set authorized key for remote user
    #   authorized_key:
    #     user: "{{ create_user }}"
    #     state: present
    #     key: "{{ copy_local_key }}"

    - name: Import Remi GPG Key
      rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present
    - name: Install Remi repo
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present
    - name: Install IUS repo
      yum:
        name: https://repo.ius.io/ius-release-el7.rpm
        state: present
    - name: Import dokku repo Key
      rpm_key:
        key: https://packagecloud.io/dokku/dokku/gpgkey
        state: present
    - name: Add dokku repo
      get_url:
        url: https://packagecloud.io/install/repositories/dokku/dokku/config_file.repo?os=centos&dist=7&source=script
        dest: /etc/yum.repos.d/dokku_dokku.repo
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Check git version
      shell: |
        set -o pipefail
        git --version | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9][^.]\).*/\1/p'
      register: CURRENT_GIT_INSTALLED_VERSION
      changed_when: false

    - name: Get git version
      debug:
        msg: "current Git version: {{ CURRENT_GIT_INSTALLED_VERSION.stdout }}"

    - name: Remove old git version
      yum:
        name: git*
        state: absent
      when: CURRENT_GIT_INSTALLED_VERSION.stdout is version(GIT_MIN_VERSION,'<')

    - name: Install system wide dependencies
      yum:
        name: "{{ sys_packages }}"
        state: present
        enablerepo: ius

    - name: Start Docker service
      with_items:
        - docker
        - nginx
      service:
        name: "{{ item }}"
        state: started
        enabled: true

    - name: Add user admin to dokku group
      user:
        name: admin
        groups:
          - dokku
        append: true

    - name: Add user admin to docker group
      user:
        name: admin
        groups:
          - docker
        append: true

    - name: Download docker-compose
      get_url:
        url: "{{ DOCKER_COMPOSE_BASEURL }}/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
        dest: ~/docker-compose

    - name: Copy docker-compose to /usr/local/bin
      copy:
        remote_src: true
        src: ~/docker-compose
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    # UFW Setup
    # - name: UFW - Allow SSH connections
    #   ufw:
    #     rule: allow
    #     name: ssh

    # - name: UFW - Deny all other incoming traffic by default
    #   ufw:
    #     state: enabled
    #     policy: deny
    #     direction: incoming
