---
- name: Install system wide dependencies
  hosts: all
  become: yes

  tasks:
    - name: Install EPEL repo
      yum:
        name: epel-release
        state: present

    - name: Import Remi GPG Key
      rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present

    - name: Install Remi repo
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present

    - name: Install system wide dependencies
      yum:
        name:
          - ddclient
          - device-mapper-persistent-data
          - firewalld
          - git
          - lvm2
          - nano
          - nginx
          - ufw
          - yum-utils
        state: present
        enablerepo: epel

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start ddclient service
      service:
        name: ddclient
        state: started
        enabled: yes

    - name: Add user admin to docker group
      user:
        name: admin
        groups: docker
        append: yes

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow all access to tcp port 443
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
