---
# performs yum update and reboots server
- name: perform yum update / reboot server
  hosts: all
  become: true

  roles:
    - geerlingguy.repo-epel

  tasks:
    - name: yum update
      debug:
        msg: "Performing Yum update of server {{ ansible_hostname }} "
    - name: Perform yum update of all packages
      yum:
        name: "*"
        state: latest
    - name: Reboot machine
      reboot:
